### ISSUE TITLE
Serving static files

### ISSUE THREAD

**Issue by cchauche** [Fusilli37/project-catwalk#36]
https://github.com/Fusilli37/project-catwalk/blob/259d128a7591e24ee2fae74dc5033aa99b4c07ba/index.js#L7-L9

Your first line in the server here sets up express.static to serve static files.  If you have set up express static correctly you shouldn't need this route to '/' which explicitly returns index.html from the public directory.  See if you can get your server working without this additional route.

**Comment by WarrenWongCodes** [comment]
Removed extra endpoint. Task completed. Closing out. @cchauche
