### ISSUE TITLE
Nice scripts, can you add more convenience?

### ISSUE THREAD

**Issue by cchauche** [Fusilli37/project-catwalk#37]
https://github.com/Fusilli37/project-catwalk/blob/259d128a7591e24ee2fae74dc5033aa99b4c07ba/package.json#L6-L8

Nice work creating a dev and production version of your build script.  It might be nice to add a start script which starts your server as well as a start dev script which starts your server using nodemon.

**Comment by WarrenWongCodes** [comment]
@cchauche Included start and start:dev scripts to stream line user experience. Including in README.md instructions. Closing out.
